Repository jorgelbg/dashflare, pull requests merged in 2020-09, with the labels that each got.

#4 Request handler refactor
  package-lock.json
  package.json
  src/handler.ts
  src/headers.ts
  src/ipinfo.ts
  test/_setup.ts
  test/handler.ts
  test/ipinfo-res.json
  test/ipinfo.ts
  test/tsconfig.json
Labels: size/L

#6 Disable workers_dev by default since we use a zone and routes
  wrangler.toml.template
Labels: size/XS

#7 Use the original URL when requests are forwarded
  src/handler.ts
  test/handler.ts
Labels: size/M
